###
  This is where you setup essential BlackSam's behaviour, namely file storage
  paths and some web-facing settings.
###
module.exports = (cfg) ->
  # HTTP Port
  # This is the port BlackSam will use for incoming HTTP.
  # NOTE 1: This is overridden if running "node server.js -p <PORT>"
  # NOTE 2: If this is commented process.env.PORT will be used
  #cfg.set 'http port', 80

  # Anti-SEO functionality. All Torrents' pages and AJAX requests will
  # be generated by a seemingly-random URL every time. Comment or change
  # to "disable" to... well, disable this.
  cfg.enable 'anti-seo'

  # Session Secret
  # User for "signing" session cookies
  cfg.set 'session secret', 'REPLACE THIS BEFORE STARTNG'

  # Max file Size
  # Any file can never exceed this size. Any files exceeding this are
  # discarded, deleted or ignored (depending on the case). In bytes.
  cfg.set 'max file size', 1024 * 1024 * 1024 #1mb

  # Path to the "marianne" directory
  # All user directories and torrents are stored here
  cfg.set 'marianne path', "#{__dirname}/../marianne"

  # Path to the "sherlock" directory
  # Search Index files are stored here
  cfg.set 'sherlock path', "#{__dirname}/../sherlock"

  # Path to the "sultanna" directory
  # Temporary files are stored here
  cfg.set 'sultanna path', "#{__dirname}/../sultanna"

  # Path to the "logs" directory
  cfg.set 'logs path' , "#{__dirname}/../logs"